package com.neochildclinic.app

object Routes {
    const val LOGIN = "login"
    const val DASHBOARD = "dashboard"
    const val ADD_PATIENT = "add_patient"
    const val PATIENT_LIST = "patient_list"
    const val PATIENT_DETAILS = "patient_details/{patientId}"
    const val EDIT_PATIENT = "edit_patient/{patientId}"
    const val EDIT_VACCINATION = "edit_vaccination/{vaccinationId}"
    const val VACCINE_INVENTORY = "vaccine_inventory"
    const val STATISTICS = "statistics"
    const val MONTHLY_FINANCE_DETAILS = "monthly_finance_details/{monthKey}"
    const val MILESTONE_PATIENTS = "milestone_patients/{milestoneKey}"
    const val BORROWED = "borrowed"
    const val DUE = "due"
    const val WASTE = "waste"
    const val ADD_VACCINE_STOCK = "add_vaccine_stock"
    const val EDIT_VACCINE_STOCK = "edit_vaccine_stock/{vaccineId}"
    const val ADD_VACCINE_DEFINITION = "add_vaccine_definition"
    const val EDIT_VACCINE_DEFINITION = "edit_vaccine_definition/{vaccineId}"
    const val ADD_BATCH = "add_batch/{vaccineId}/{brandName}"
    const val EDIT_BATCH = "edit_batch/{batchId}?vaccineId={vaccineId}&brandName={brandName}"
    const val SETTINGS = "settings"
    const val PROFILE = "profile"
    const val NOTIFICATION_SETTINGS = "notification_settings"
    const val INVENTORY_SETTINGS = "inventory_settings"
    const val BACKUP_SETTINGS = "backup_settings"
    const val SECURITY_SETTINGS = "security_settings"
    const val HELP_SUPPORT = "help_support"
    const val PRIVACY_POLICY = "privacy_policy"
    const val TERMS_OF_SERVICE = "terms_of_service"
    const val APP_UPDATE = "app_update"
    const val SYNC = "sync"
    const val AUDIT_LOGS = "audit_logs"
    const val MANAGE_STAFF = "manage_staff"
    const val STAFF_DETAILS = "staff_details/{staffId}"
    const val ADD_STAFF = "add_staff"
    const val EDIT_STAFF = "edit_staff/{staffId}"
    const val SEARCH = "search"
    const val ADD_VACCINE = "add_vaccine"
    const val ADD_VACCINE_FOR_PATIENT = "add_vaccine/{patientId}"
    const val ADD_CONSULTATION = "add_consultation/{patientId}"
    const val EDIT_CONSULTATION = "edit_consultation/{consultationId}"
    const val COMPLETED_DISMISSED = "completed_dismissed"
    const val TODAY_PATIENTS = "today_patients"
}
